### ISSUE TITLE
Migrate to kiwiproject

### ISSUE THREAD

**Issue by chrisrohr** [elucidation-project/elucidation#5]
- [x] Setup CI/Github Actions (build and sonar)
- [x] Migrate packages to org.kiwiproject
- [x] Upgrade to latest kiwi parent and bom (bump to 5.0.0)
- [ ] Refactor release process to match other kiwi library setups

**Comment by sleberknight** [comment]
@chrisrohr Should be able to use my recent enhancements to the maven release scripts. I modified all the kiwi repos.
